camera:
  source: 0
  width: 640
  height: 480
  fps_request: 30
  backend: "auto"
  buffersize: 2
  gstreamer:
    pipeline: ""            # 留空自动生成 nvarguscamerasrc 管线
    sensor_id: 0
    capture_width: 1280
    capture_height: 720
    display_width: 1280
    display_height: 720
    framerate: 30
    flip_method: 0

runtime:
  async:
    enabled: false
    queue_size: 4
    drop_policy: "oldest"    # "oldest" | "newest"
    max_latency_ms: 180.0    # 超过该延迟丢弃旧帧，0 表示不限
    result_timeout_ms: 250.0
  hot_reload:
    enabled: false
    interval_sec: 2.0
    restart_on_camera_change: true

preview:
  show_fps: true
  compare:
    enable: true
    layout: "h"        # "h" | "v"
    label_raw: "RAW"
    label_proc: "PROC"
    divider_px: 4
  record:
    enable: false
    path: out_compare.mp4
    fps: 30

preprocess:
  enabled: true
  chain:
    - name: CLAHEDehaze
      params:
        space: "YCrCb"
        clip_limit: 2.0
        tile_grid: 8
    - name: MedianDerain
      params:
        ksize: 3
  auto_gate:
    enable_low_contrast_gate: false
    contrast_thresh: 20.0

detect:
  enabled: true
  backend: "ultralytics"         # tensorrt 时改为 "tensorrt"
  model: "yolov8n.pt"            # 也可用 yolov5n.pt / yolov8s.pt 等
  engine: ""                     # 指向 .engine 文件（backend=tensorrt 时）
  device: "auto"                 # "auto" | "cpu" | "cuda:0"
  conf_thres: 0.25
  iou_thres: 0.7
  max_det: 100
  imgsz: 640
  warmup_runs: 0
  half: true
  # COCO 类别筛选：2=car,3=motorcycle,5=bus,7=truck（也可加 1=bicycle, 0=person）
  classes_keep: [0, 2, 3, 5, 7]

tracking:
  enabled: true
  backend: "sort"
  max_staleness: 1.2      # 轨迹超时（秒）
  min_hits: 3             # 连续命中次数达到后才稳定
  iou_threshold: 0.35
  speed_window: 0.8       # 速度估计时间窗（秒）

geometry:
  enabled: false
  projector:
    type: "homography"
    image_points: []      # 示例: [[x1,y1], [x2,y2], ...]
    world_points: []      # 示例: [[X1,Y1], ...] 单位米
    origin: [0.0, 0.0]
    max_distance: 1000.0  # 米，避免异常值

vis:
  draw:
    det: true
    thickness: 2
    font_scale: 0.6
