camera:
  source: 0
  width: 640
  height: 480
  fps_request: 30
  backend: "auto"

preview:
  show_fps: true
  compare:
    enable: true
    layout: "h"        # "h" | "v"
    label_raw: "RAW"
    label_proc: "PROC"
    divider_px: 4
  record:
    enable: false
    path: out_compare.mp4
    fps: 30

preprocess:
  enabled: true
  chain:
    - name: CLAHEDehaze
      params:
        space: "YCrCb"
        clip_limit: 2.0
        tile_grid: 8
    - name: MedianDerain
      params:
        ksize: 3
  auto_gate:
    enable_low_contrast_gate: false
    contrast_thresh: 20.0
